---
language: ruby
sudo: false
cache: bundler

before_install:
  - type bundle >/dev/null 2>&1 || gem install bundler -v '< 2'

rvm:
  - 2.2.10
  - 2.3.8
  - 2.4.5
  - 2.5.3
  - 2.6.0

gemfile:
  - gemfiles/active_record_4.2.gemfile
  - gemfiles/active_record_5.0.gemfile
  - gemfiles/active_record_5.1.gemfile
  - gemfiles/active_record_5.2.gemfile

matrix:
  include:
    - gemfile: gemfiles/active_record_4.2.gemfile
      rvm: 2.1.10
    - gemfile: gemfiles/active_record_edge.gemfile
      rvm: 2.5.3
    - gemfile: gemfiles/active_record_edge.gemfile
      rvm: 2.6.0
