---
language: ruby
sudo: false
cache: bundler

rvm:
  - 2.2.10
  - 2.3.7
  - 2.4.4
  - 2.5.1

gemfile:
  - gemfiles/active_record_4.2.gemfile
  - gemfiles/active_record_5.0.gemfile
  - gemfiles/active_record_5.1.gemfile
  - gemfiles/active_record_5.2.gemfile
  - gemfiles/active_record_edge.gemfile

matrix:
  include:
    - gemfile: gemfiles/active_record_4.2.gemfile
      rvm: 2.1.10
  exclude:
    - gemfile: gemfiles/active_record_edge.gemfile
      rvm: 2.2.10
    - gemfile: gemfiles/active_record_edge.gemfile
      rvm: 2.3.7
